export { normalizeDescription } from "./normalize"
export { suggestCategory } from "./matcher"
export { classifyTransaction } from "./ai-classifier"
export { upsertCategoryPattern } from "./upsert-pattern"
export type { MatchSuggestion, MatchConfidence, StoredPattern } from "./types"
