/**
 * Domain types for the anamnese / questionnaire form builder.
 *
 * A FormTemplate holds a mutable `draftFields` array. Publishing snapshots it
 * into an immutable FormVersion. Responses always reference a version, so the
 * rendered question set is faithful to the moment the patient answered.
 */

export type FormFieldType =
  | "section"
  | "short_text"
  | "long_text"
  | "single_choice"
  | "multiple_choice"
  | "dropdown"
  | "scale_0_10"
  | "date"
  | "yes_no"
  | "info_consent"

export interface FormFieldCondition {
  fieldId: string
  equals: string | number | boolean
}

export interface FormField {
  /** Stable within the template (generated by makeFieldId). */
  id: string
  type: FormFieldType
  label: string
  description?: string
  required?: boolean
  /** Required (non-empty) for single_choice | multiple_choice | dropdown. */
  options?: string[]
  /** Read-only text shown for info_consent fields (LGPD / consent copy). */
  infoText?: string
  /** Show this field only when a previous field's answer equals a value. */
  visibleWhen?: FormFieldCondition
}

export type AnswerValue = string | string[] | number | boolean
export type FormAnswers = Record<string, AnswerValue>

/** Field types that never collect an answer (don't count toward progress). */
export const NON_ANSWERABLE_TYPES: ReadonlySet<FormFieldType> = new Set<FormFieldType>([
  "section",
])

export const FIELD_TYPE_LABELS: Record<FormFieldType, string> = {
  section: "Seção (cabeçalho)",
  short_text: "Texto curto",
  long_text: "Texto longo",
  single_choice: "Escolha única",
  multiple_choice: "Múltipla escolha",
  dropdown: "Lista suspensa",
  scale_0_10: "Escala 0–10",
  date: "Data",
  yes_no: "Sim / Não",
  info_consent: "Termo de consentimento",
}

/** Field types whose value comes from a fixed list of options. */
export const CHOICE_TYPES: ReadonlySet<FormFieldType> = new Set<FormFieldType>([
  "single_choice",
  "multiple_choice",
  "dropdown",
])

export const SHORT_TEXT_MAX = 200
export const LONG_TEXT_MAX = 5000
